
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControlCalidad.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Proyectoes = new HashSet<Proyecto>();

    }


    public string cedulaPK { get; set; }

    public string nombreP { get; set; }

    public string apellido1 { get; set; }

    public string apellido2 { get; set; }

    public string telefono { get; set; }

    public string correo { get; set; }

    public string provincia { get; set; }

    public string canton { get; set; }

    public string distrito { get; set; }

    public string direccionExacta { get; set; }

    public Nullable<System.DateTime> fechaNacimiento { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Proyecto> Proyectoes { get; set; }

}

}
