
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControlCalidad.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Habilidade
{

    public string cedula_empleadoFK { get; set; }

    public string categoriaPK { get; set; }

    public string descripcionPK { get; set; }



    public virtual Empleado Empleado { get; set; }

}

}
