
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControlCalidad.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TieneAsignado
{

    public string cedula_empleadoFK { get; set; }

    public int id_requerimientoFK { get; set; }

    public int id_proyectoFK { get; set; }

    public Nullable<float> horasDedicas { get; set; }



    public virtual Requerimiento Requerimiento { get; set; }

    public virtual Tester Tester { get; set; }

}

}
